03 mongodb
Mykokola/nodejs-homework pull request #2
Opened 2023-09-21 01:13 UTC by Mykokola

2023-09-21 01:14 UTC, Mykokola commented
зараз в канаді тому провайдер взяв в вірджинії щоб швидше грузило

2023-09-21 06:50 UTC, ceREAL133 requested changes

2023-09-21 06:50 UTC, ceREAL133 commented on adapters/express/api/contacts.js
>    try {
роут повинен викликати функцію, а не описувати нову колбек функцію,
типу так: `router.post("/", validateBody(addJoiSchema), addContact);`

2023-09-21 17:33 UTC, ceREAL133 requested changes

2023-09-21 17:33 UTC, ceREAL133 commented on adapters/express/api/contacts.js
> +//   } catch (error) {
видаліть ці коменти

2023-09-22 08:03 UTC, ceREAL133 approved these changes

2023-09-22 12:33 UTC, merged